# Generated by Django 2.2.4 on 2019-08-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=200000000, upload_to=''),
        ),
    ]
