# Generated by Django 2.2.4 on 2019-08-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20190823_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
