# Generated by Django 2.2.4 on 2019-08-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20190823_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
